# Generated by Django 5.2 on 2025-10-19 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_score', models.FloatField(help_text='Predicted interest score (0-1)')),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_predictions', to='products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Recommendation',
                'verbose_name_plural': 'Category Recommendations',
                'indexes': [models.Index(fields=['user', '-prediction_score'], name='recommendat_user_id_908fcb_idx'), models.Index(fields=['-predicted_at'], name='recommendat_predict_26685f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('frequently_bought', 'Frequently Bought Together'), ('similar', 'Similar Products'), ('contextual', 'Contextual Recommendations')], max_length=20)),
                ('score', models.FloatField(help_text='Recommendation confidence score (0-1)')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product for which recommendations are made', on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='products.product')),
                ('recommended_product', models.ForeignKey(help_text='The recommended product', on_delete=django.db.models.deletion.CASCADE, related_name='target_recommendations', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Recommendation',
                'verbose_name_plural': 'Product Recommendations',
                'indexes': [models.Index(fields=['product', 'recommendation_type', '-score'], name='recommendat_product_3c164c_idx'), models.Index(fields=['-generated_at'], name='recommendat_generat_61776e_idx')],
                'unique_together': {('product', 'recommended_product', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Browsing History',
                'verbose_name_plural': 'User Browsing Histories',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='recommendat_user_id_f2ea1f_idx'), models.Index(fields=['session_id', '-viewed_at'], name='recommendat_session_856b90_idx'), models.Index(fields=['product', '-viewed_at'], name='recommendat_product_def49d_idx')],
            },
        ),
    ]
