# Generated by Django 5.2 on 2025-10-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Performance',
                'verbose_name_plural': 'Category Performance Metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='analytics_c_period__bf1263_idx'), models.Index(fields=['category', '-period_start'], name='analytics_c_categor_3f21ae_idx'), models.Index(fields=['-generated_at'], name='analytics_c_generat_4c2cdc_idx')],
                'unique_together': {('category', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('views', models.IntegerField(default=0, help_text='Total product views from browsing history')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performance Metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='analytics_p_period__1acc87_idx'), models.Index(fields=['product', '-period_start'], name='analytics_p_product_35d4c0_idx'), models.Index(fields=['-generated_at'], name='analytics_p_generat_d41f9f_idx'), models.Index(fields=['-total_sales'], name='analytics_p_total_s_07c526_idx'), models.Index(fields=['-views'], name='analytics_p_views_e6ee04_idx')],
                'unique_together': {('product', 'period_start', 'period_end')},
            },
        ),
    ]
