# Generated by Django 5.2.5 on 2025-11-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='predicted_category',
            field=models.ForeignKey(blank=True, help_text='ML-predicted preferred category for personalization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_users', to='storefront.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
