# Generated by Django 5.2 on 2025-10-19 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='The admin who wrote this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this customer')),
                ('customer_since', models.DateField(auto_now_add=True)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('preferred_category', models.ForeignKey(blank=True, help_text="Customer's preferred product category", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_customers', to='products.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profiles',
                'ordering': ['-customer_since'],
            },
        ),
    ]
