# Generated by Django 5.2 on 2025-10-19 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product')),
            ],
            options={
                'db_table': 'stock_alerts',
                'ordering': ['is_resolved', '-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='stock_alert_is_reso_4c3ba9_idx'), models.Index(fields=['product', 'is_resolved'], name='stock_alert_product_67c7af_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock increase, negative for decrease')),
                ('reason', models.TextField(help_text='Reason for this stock movement')),
                ('reference_number', models.CharField(blank=True, help_text='Order number, invoice number, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_before', models.IntegerField(default=0)),
                ('stock_after', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who made this stock change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='stock_movem_product_407bbc_idx'), models.Index(fields=['movement_type', '-created_at'], name='stock_movem_movemen_829843_idx')],
            },
        ),
    ]
